services:
  mc:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    ports:
      - "42069:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.1"
    volumes:
      - ./data:/data
    DATAPACKS:
      - /datapacks/idle-timeout-datapack
    RCON_CMDS_STARTUP: |-
      function idle_timeout:init
    RCON_CMDS_LAST_DISCONNECT: |-
      function idle_timeout:lastplayerleave
