services:
  mc:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
      - "./datapacks:/datapacks"
      - "./modpacks/server:/modpacks:ro"
    environment:
      MOTD: "Journey into the wilderness..."
      ICON: "https://www.animesenpai.net/wp-content/uploads/2023/12/GBX93m_XIAACW6r.jpg.webp"
      LEVEL: "diddycraft"
      SEED: -96974983
      ALLOW_FLIGHT: "TRUE"
      # VERSION & JVM FLAGS
      EULA: "TRUE"
      MODPACK_PLATFORM: "AUTO_CURSEFORGE"
      CF_API_KEY: ${CF_API_KEY}
      MEMORY: "4096M"
      USE_MEOWICE_FLAGS: "true"
      # CONTENT
      DATAPACKS: "/datapacks/idle_timeout"
      CF_MODPACK_ZIP: "/modpacks/Revelations_1.21.1_NF_SERVER-v1.0.zip"
      CF_SLUG: "custom"
      # PERMISSIONS & ADMIN
      RCON_PASSWORD: ${MC_RCON_PASSWORD}
      OPS: "Theriel"
      FUNCTION_PERMISSION_LEVEL: 4
      RCON_CMDS_STARTUP: |-
        function idle_timeout:init
      RCON_CMDS_LAST_DISCONNECT: |-
        function idle_timeout:lastplayerleave
